[workspace]
members = ["src-tauri","tauri-plugin-clipboard-pal", "clipboard-listener"]
resolver = "3"

[workspace.package]
authors = ["jingchuan"]
description = "A ClipPal App"
edition = "2024"
name = "Clip-Pal"
version = "0.1.0"


[workspace.dependencies]
thiserror = "2"
uuid = "1"
clipboard-rs = "0.2.1"
base64 = "0.22.1"
image = "0.25.1"
serde = {version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1.0", features = ["full"] } 
async-channel = "2.3.1"
async-trait = "0.1"
rbs = { version = "=4.5"}
rbatis = { version = "=4.5"}
rbdc-sqlite = { version = "=4.5" }
state = {version = "0.6.0"}
tauri = {version = "=2.5.1", features = ["tray-icon", "image-png"] }
tauri-plugin-http = "=2.4.4"
tauri-plugin-opener = "2"
tauri-plugin-single-instance = "2"
md5 = "0.7.0"
anyhow = "1.0" 
directories = "6"